services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4144
      POSTGRES_DB: faceid_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

  celery-worker:
    build: .
    restart: unless-stopped
    env_file: .env
    command: celery -A app.celery_app worker --loglevel=info --concurrency=4 --max-tasks-per-child=100
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

volumes:
  pgdata:
