"""initial

Revision ID: 0918ce189ccf
Revises: e3f4a5b6c7d8
Create Date: 2026-03-16 14:50:30.811781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0918ce189ccf'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_session_smena_number_key', 'test_session_smena', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('test_session_smena_number_key', 'test_session_smena', ['number'])
    # ### end Alembic commands ###
