"""refresh_token_hash_and_family

Revision ID: 305d0d1426c2
Revises: f5ea5f5ab3ed
Create Date: 2026-04-29 17:21:47.562696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305d0d1426c2'
down_revision: Union[str, None] = 'f5ea5f5ab3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('replaced_by_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('reuse_detected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint('uq_cheating_logs_student_id', 'cheating_logs', type_='unique')
    op.drop_index('ix_cheating_logs_student_id', table_name='cheating_logs')
    op.create_index(op.f('ix_cheating_logs_student_id'), 'cheating_logs', ['student_id'], unique=True)
    op.drop_constraint('uq_student_blacklist_imei', 'student_blacklist', type_='unique')
    op.drop_index('ix_student_blacklist_imei', table_name='student_blacklist')
    op.create_index(op.f('ix_student_blacklist_imei'), 'student_blacklist', ['imei'], unique=True)
    op.drop_constraint('uq_student_logs_student_id', 'student_logs', type_='unique')
    op.drop_index('ix_student_logs_student_id', table_name='student_logs')
    op.create_index(op.f('ix_student_logs_student_id'), 'student_logs', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_logs_student_id'), table_name='student_logs')
    op.create_index('ix_student_logs_student_id', 'student_logs', ['student_id'], unique=False)
    op.create_unique_constraint('uq_student_logs_student_id', 'student_logs', ['student_id'])
    op.drop_index(op.f('ix_student_blacklist_imei'), table_name='student_blacklist')
    op.create_index('ix_student_blacklist_imei', 'student_blacklist', ['imei'], unique=False)
    op.create_unique_constraint('uq_student_blacklist_imei', 'student_blacklist', ['imei'])
    op.drop_index(op.f('ix_cheating_logs_student_id'), table_name='cheating_logs')
    op.create_index('ix_cheating_logs_student_id', 'cheating_logs', ['student_id'], unique=False)
    op.create_unique_constraint('uq_cheating_logs_student_id', 'cheating_logs', ['student_id'])
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
