"""initial

Revision ID: 543115174cab
Revises: d2f3a4b5c6e7
Create Date: 2026-03-16 13:40:41.813987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543115174cab'
down_revision: Union[str, None] = 'd2f3a4b5c6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'region_id')
    # ### end Alembic commands ###
