"""initial

Revision ID: 687c8f71aa65
Revises: a8b9c0d1e2f3
Create Date: 2026-03-17 17:35:04.226533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687c8f71aa65'
down_revision: Union[str, None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gender_id'), 'gender', ['id'], unique=False)
    op.add_column('student_ps_data', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_ps_data', 'gender', ['gender_id'], ['id'])
    op.drop_column('student_ps_data', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_ps_data', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_ps_data', type_='foreignkey')
    op.drop_column('student_ps_data', 'gender_id')
    op.drop_index(op.f('ix_gender_id'), table_name='gender')
    op.drop_table('gender')
    # ### end Alembic commands ###
