"""initial

Revision ID: 788bdbd52ccf
Revises: 543115174cab
Create Date: 2026-03-16 14:00:58.522226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788bdbd52ccf'
down_revision: Union[str, None] = '543115174cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_region_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'zone', ['zone_id'], ['id'])
    op.drop_column('users', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_region_id_fkey', 'users', 'regions', ['region_id'], ['id'])
    op.drop_column('users', 'zone_id')
    # ### end Alembic commands ###
