"""initial

Revision ID: 7e38ced2cc6a
Revises: a0ef5643c0c2
Create Date: 2026-03-15 23:53:53.805645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e38ced2cc6a'
down_revision: Union[str, None] = 'a0ef5643c0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('zone_number_key', 'zone', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('zone_number_key', 'zone', ['number'])
    # ### end Alembic commands ###
