"""initial

Revision ID: c689903fd146
Revises: 82ae2f652233
Create Date: 2026-03-16 15:42:55.229967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c689903fd146'
down_revision: Union[str, None] = '82ae2f652233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_key_key', 'tests', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tests_key_key', 'tests', ['key'])
    # ### end Alembic commands ###
