"""baseline

Revision ID: c82a07714076
Revises: 305d0d1426c2
Create Date: 2026-04-29 17:46:28.089372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82a07714076'
down_revision: Union[str, None] = '305d0d1426c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_login_attempts_attempted_at'), 'failed_login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_id'), 'failed_login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_ip_address'), 'failed_login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_reason'), 'failed_login_attempts', ['reason'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_username'), 'failed_login_attempts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_login_attempts_username'), table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_reason'), table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_ip_address'), table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_id'), table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_attempted_at'), table_name='failed_login_attempts')
    op.drop_table('failed_login_attempts')
    # ### end Alembic commands ###
